replicaCount: 1

image:
  repository: ornikar-world
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"
  containerPort: 3000
  
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

hosts:
- host: ornikar.dev
  path: /world
  middleware:
    enabled: false

middleware:
  enabled: false
