apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "world.fullname" . }}
  labels:
    {{- include "world.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.hosts }}
    - match: Host(`{{ .host }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ include "world.fullname" $ }}
          port: 3000
      {{- if .middleware.enabled }}
      middlewares:
        {{- range $middleware := .middleware.middlewares }}
        - name: {{ $middleware.name }}
        {{- end }}
      {{- end }}
    {{- end }}
