{{- if .Values.middleware.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.middleware.prefix }}
{{- end }}

